name: Build (Windows, clang-cl, Ninja)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Set up build directory
      id: vars
      shell: bash
      run: echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (clang-cl + Ninja)
      run: >
        cmake -B ${{ steps.vars.outputs.build-dir }}
        -G "Ninja"
        -DCMAKE_C_COMPILER=clang-cl
        -DCMAKE_CXX_COMPILER=clang-cl
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: ninja -C ${{ steps.vars.outputs.build-dir }}

    - name: Test
      working-directory: ${{ steps.vars.outputs.build-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: css-sdk-${{ matrix.build_type }}
        path: |
          output/*.dll
          output/*.pdb
